### PR TITLE
dedalo: disable offloads also when a vlan is used

### PR DESCRIPTION
**Pull request by Amygos**
Disable the Ethernet offloads in the physical interface, instead on the
virtual vlan interface.

NethServer/dev#6343

### CODE REVIEW

**Review by gsanchietti — COMMENTED** [review]
With this patch you're going to disable the offload from the physical device which could be benefit from such feature.

Why this thing is needed?

**Comment by Amygos** [comment]
> With this patch you're going to disable the offload from the physical device which could be benefit from such feature.
> 
> Why this thing is needed?

Coova-chilli don't support well the Ethernet offloading, resulting in a cut of the total available bandwidth of the interface.
In the issue NethServer/dev#6264 we had choose to to disable the Ethernet offloads in case is uses as hotspot interface by the captive portal.

This PR fix the aspected behaviour.

**Comment by gsanchietti** [comment]
Let's say you have an ethernet named `eth0`, configured as:
- `eth0`: green interface
- `eth0.1`: vlan for hotspot

With this patch you're going to disable the offload on the green interface which could benefit from such feature.

If you're going down this path, you should handle also all other virtual interfaces like bond and bridge.

**Review by gsanchietti — APPROVED** [review]
I do not like this approach, but it seems that VLAN are often used for hotspot configuration.

Let's go with the current modification and leave bridge/bond aside.

**Pull request merged**
